// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const addMagazine = `-- name: AddMagazine :execresult
INSERT INTO magazines (
	number,
	date,
	location
) VALUES (
	?, ?, ?
)
`

type AddMagazineParams struct {
	Number   int64
	Date     int64
	Location string
}

func (q *Queries) AddMagazine(ctx context.Context, arg AddMagazineParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addMagazine, arg.Number, arg.Date, arg.Location)
}

const getMagazine = `-- name: GetMagazine :one
SELECT id, inserted, number, date, location FROM magazines
WHERE id = ? LIMIT 1
`

func (q *Queries) GetMagazine(ctx context.Context, id string) (Magazine, error) {
	row := q.db.QueryRowContext(ctx, getMagazine, id)
	var i Magazine
	err := row.Scan(
		&i.ID,
		&i.Inserted,
		&i.Number,
		&i.Date,
		&i.Location,
	)
	return i, err
}

const getMagazineByNumber = `-- name: GetMagazineByNumber :one
SELECT id, inserted, number, date, location FROM magazines
WHERE number = ? LIMIT 1
`

func (q *Queries) GetMagazineByNumber(ctx context.Context, number int64) (Magazine, error) {
	row := q.db.QueryRowContext(ctx, getMagazineByNumber, number)
	var i Magazine
	err := row.Scan(
		&i.ID,
		&i.Inserted,
		&i.Number,
		&i.Date,
		&i.Location,
	)
	return i, err
}

const listMagazines = `-- name: ListMagazines :many
SELECT id, inserted, number, date, location FROM magazines
ORDER BY date
LIMIT ? OFFSET ?
`

type ListMagazinesParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListMagazines(ctx context.Context, arg ListMagazinesParams) ([]Magazine, error) {
	rows, err := q.db.QueryContext(ctx, listMagazines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Magazine
	for rows.Next() {
		var i Magazine
		if err := rows.Scan(
			&i.ID,
			&i.Inserted,
			&i.Number,
			&i.Date,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMagazine = `-- name: RemoveMagazine :exec
DELETE FROM magazines
WHERE id = ?
`

func (q *Queries) RemoveMagazine(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, removeMagazine, id)
	return err
}
