// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import ()

type Magazine struct {
	ID       string
	Inserted int64
	Number   int64
	Date     int64
	Location string
}
